name: emarkproject
version: master
summary: decentralized peer-to-peer platform
description: |
  The eMark Project is a decentralized peer-to-peer platform, created under an
  open source license, featuring a built-in cryptocurrency, end-to-end
  encrypted messaging and decentralized marketplace. The decentralized network
  aims to provide anonymity and privacy for everyone through a simple
  user-friendly interface by taking care of all the advanced cryptography in
  the background.
grade: devel
confinement: strict

apps:
  daemon:
    command: eMarkd
    plugs: [network, network-bind]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  qt:
    command: desktop-launch eMark-qt
    plugs: [network, network-bind, unity7]
    desktop: eMark.desktop

parts:
  emarkproject:
    source: https://github.com/emarkproject/eMark
    source-type: git
    source-tag: master
    plugin: autotools
    # XXX We don't want to copy the full blockchain every time that the snap is
    # updated, but there's no way to define a default data dir in bitcoin-qt.
    # Also, it would be better if we could split the wallet from the blockchain
    # https://github.com/bitcoin/bitcoin/issues/3214
    # -- elopio-20170308
    override-build: | 
      git apply $SNAPCRAFT_STAGE/default_data_dir.patch
      snapcraftctl build
    build-packages:
    # build-essential libtool autotools-dev autoconf pkg-config libssl-dev libboost-all-dev
    # libqrencode-dev libminiupnpc-dev libevent-dev libcap-dev libseccomp-dev git bsdmainutils
    # software-properties-common libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
      - build-essential
      - libdb++-dev
      - libboost-all-dev
      
      - g++
      - pkg-config
      - libssl-dev
      - libevent-dev
      - bsdmainutils
      - libcap-dev
      - libseccomp-dev
      # Boost.
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - libboost-thread-dev
      # Optional.
      - libminiupnpc-dev
      - libzmq3-dev
      # GUI.
      - libqt5gui5
      - libqt5core5a
      - libqt5dbus5
      - qttools5-dev
      - qttools5-dev-tools
      - libprotobuf-dev
      - protobuf-compiler
      # Optional.
      - libqrencode-dev
    stage-packages: [ca-certificates]
    after:
      - berkeleydb
      - desktop-qt5
      - patches
  berkeleydb:
    source: http://download.oracle.com/berkeley-db/db-4.8.30.tar.gz
    plugin: nil
    override-build: |
      cd build_unix
      ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=$SNAPCRAFT_PART_INSTALL
      snapcraftctl build
      make install
    prime:
      - -*
  patches:
    source: snap/patches
    plugin: dump
    prime:
      - -*
  desktop:
    source: snap/gui
    plugin: dump
